
    create table hibernate_sequences (
       sequence_name varchar(255) not null,
        next_val bigint,
        primary key (sequence_name)
    );

    insert into hibernate_sequences(sequence_name, next_val) values ('default',0);

    create table tb_disco_removivel (
       img_url TEXT,
        id bigint not null,
        tipo_item_id bigint,
        primary key (id)
    );

    create table tb_doacao (
       id bigint generated by default as identity,
        descricao varchar(255),
        valor float,
        doador_id bigint,
        primary key (id)
    );

    create table tb_feedback (
       id bigint generated by default as identity,
        comentario varchar(255),
        img_url TEXT,
        autor_id bigint,
        visita_id bigint,
        primary key (id)
    );

    create table tb_item (
       dtype varchar(31) not null,
        id bigint not null,
        altura float,
        ano integer,
        espessura float,
        informacoes TEXT,
        largura float,
        nome varchar(255),
        quantidade integer,
        doacao_id bigint,
        primary key (id)
    );

    create table tb_link (
       id bigint generated by default as identity,
        url TEXT,
        item_id bigint,
        primary key (id)
    );

    create table tb_memoria (
       id bigint not null,
        primary key (id)
    );

    create table tb_oficina (
       id bigint generated by default as identity,
        duracao integer,
        horario timestamp,
        local varchar(255),
        resumo TEXT,
        titulo varchar(255),
        palestrante_id bigint,
        primary key (id)
    );

    create table tb_papel (
       id bigint generated by default as identity,
        descricao varchar(255),
        primary key (id)
    );

    create table tb_periferico (
       img_url TEXT,
        id bigint not null,
        tipo_item_id bigint,
        primary key (id)
    );

    create table tb_pessoa (
       id bigint generated by default as identity,
        curriculo TEXT,
        email varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table tb_pessoa_papel (
       pessoa_id bigint not null,
        papel_id bigint not null,
        primary key (pessoa_id, papel_id)
    );

    create table tb_placa (
       classificacao varchar(255),
        id bigint not null,
        primary key (id)
    );

    create table tb_processador (
       id bigint not null,
        primary key (id)
    );

    create table tb_software (
       id bigint not null,
        primary key (id)
    );

    create table tb_tipo_item (
       id bigint generated by default as identity,
        descricao varchar(255),
        primary key (id)
    );

    create table tb_visita (
       id bigint generated by default as identity,
        data_fim timestamp,
        data_inicio timestamp,
        local varchar(255),
        responsavel_id bigint,
        primary key (id)
    );

    create table tb_visita_pessoa (
       visita_id bigint not null,
        pessoa_id bigint not null,
        primary key (visita_id, pessoa_id)
    );

    alter table tb_pessoa 
       add constraint UK_snyv3i2fnu0tr7ort270s0yfv unique (email);

    alter table tb_disco_removivel 
       add constraint FKeyobsrtdeounlljnqln2b9exj 
       foreign key (tipo_item_id) 
       references tb_tipo_item;

    alter table tb_disco_removivel 
       add constraint FKjo5xk6ltf9gunnaj8t1vdmf7y 
       foreign key (id) 
       references tb_item;

    alter table tb_doacao 
       add constraint FKmbvvstgd4fp5x9ecpmvrudonv 
       foreign key (doador_id) 
       references tb_pessoa;

    alter table tb_feedback 
       add constraint FKp2uwiq7olbgn6xt6mj44mwrg6 
       foreign key (autor_id) 
       references tb_pessoa;

    alter table tb_feedback 
       add constraint FK4ewacb27kwxysyllmk01bnvd1 
       foreign key (visita_id) 
       references tb_visita;

    alter table tb_item 
       add constraint FKgyexxfy99djgacumrpi7jarmy 
       foreign key (doacao_id) 
       references tb_doacao;

    alter table tb_link 
       add constraint FKiuwqkcxnlroadsl6ufrm8grd8 
       foreign key (item_id) 
       references tb_item;

    alter table tb_memoria 
       add constraint FK2avuvr3jnsvk8uvsrksuc4id9 
       foreign key (id) 
       references tb_item;

    alter table tb_oficina 
       add constraint FK4vfyu08n9w8q4tvp0an5f5ebb 
       foreign key (palestrante_id) 
       references tb_pessoa;

    alter table tb_periferico 
       add constraint FK1pid2id6xu7qs8hsb5f8svk9w 
       foreign key (tipo_item_id) 
       references tb_tipo_item;

    alter table tb_periferico 
       add constraint FKjs3ywb4jthxmmxdt8mgfjj8fa 
       foreign key (id) 
       references tb_item;

    alter table tb_pessoa_papel 
       add constraint FKenita45xgba8hrs7dwtb9qo7k 
       foreign key (papel_id) 
       references tb_papel;

    alter table tb_pessoa_papel 
       add constraint FKol6t9pohsu9wkyfxbo2wrx5xg 
       foreign key (pessoa_id) 
       references tb_pessoa;

    alter table tb_placa 
       add constraint FKs4jtm53g45g10u9eptbl0y41n 
       foreign key (id) 
       references tb_item;

    alter table tb_processador 
       add constraint FKoknxvaw5ly23y4th4x4c9rlp1 
       foreign key (id) 
       references tb_item;

    alter table tb_software 
       add constraint FKt5cayq0ciqilv9s0p7ipdtfpc 
       foreign key (id) 
       references tb_item;

    alter table tb_visita 
       add constraint FK91657kwxuc3e8nkwoqktvowpu 
       foreign key (responsavel_id) 
       references tb_pessoa;

    alter table tb_visita_pessoa 
       add constraint FKbdyxu641ikfn1vu80d1y9ereg 
       foreign key (pessoa_id) 
       references tb_pessoa;

    alter table tb_visita_pessoa 
       add constraint FKpqj2715inb5ihrhptowj18dp0 
       foreign key (visita_id) 
       references tb_visita;

INSERT INTO tb_papel (descricao) VALUES ('Visitante');
INSERT INTO tb_papel (descricao) VALUES ('Palestrante');
INSERT INTO tb_papel (descricao) VALUES ('Responsavel');